Repository pkeilbach/htwg-practical-nlp, pull requests merged in 2024-12, with the labels that each got.

#180 chore: add OOV abbreviation
  docs/lectures/language_models.md
  includes/abbreviations.md
Labels: documentation

#190 Add autoreload functionality to jupyter notebooks
  notebooks/data_acquisition.ipynb
  notebooks/logistic_regression.ipynb
  notebooks/minimum_edit_distance.ipynb
  notebooks/naive_bayes.ipynb
  notebooks/preprocessing.ipynb
  notebooks/vector_space_models.ipynb
Labels: enhancement, assignments

#178 POS abbreviation
  docs/lectures/introduction.md
  docs/lectures/minimum_edit_distance.md
  docs/lectures/preprocessing.md
  includes/abbreviations.md
Labels: documentation

#193 Added tolerance to test_cosine_similarity
  tests/htwgnlp/test_embeddings.py
Labels: bug, assignments

#195 Change assignment policy
  CONTRIBUTING.md
  README.md
  docs/assignments.md
  docs/course_profile.md
  docs/faq.md
  docs/index.md
  docs/presentations.md
Labels: assignments

#196 Add FAQ that lectures are not mandatory
  docs/faq.md
Labels: documentation

#197 Add references: literature and podcast episode
  docs/course_profile.md
  docs/lectures/further_reading.md
Labels: documentation

#200 Session 4 lecture updates
  docs/lectures/logistic_regression.md
  docs/lectures/naive_bayes.md
Labels: documentation

#206 Add precommit strip ipynb
  .pre-commit-config.yaml
  notebooks/logistic_regression.ipynb
  notebooks/naive_bayes.ipynb
  notebooks/preprocessing.ipynb
  notebooks/vector_space_models.ipynb
Labels: enhancement, devops

#208 Add a index slicing exercise to Python basics assignment
  src/htwgnlp/python_basics.py
  tests/htwgnlp/test_python_basics.py
Labels: assignments

#210 Notebook for minimum edit distance is now assignment 5
  notebooks/minimum_edit_distance.ipynb
Labels: assignments

#209 New jupyterlab dependency
  Makefile
  docs/assignments.md
  docs/getting_started.md
  pyproject.toml
Labels: devops

#211 Update word embeddings lecture
  docs/lectures/word_embeddings.md
Labels: lecture

#212 Incorporate Raschka chapter 2.1
  docs/lectures/word_embeddings.md
Labels: lecture
