Repository pkeilbach/htwg-practical-nlp, pull requests merged in 2024-11, with the labels that each got.

#160 Add assignment for Python basics
  src/htwgnlp/python_basics.py
  tests/htwgnlp/files/test_data.json
  tests/htwgnlp/test_python_basics.py
Labels: assignments

#161 Update preprocessing lecture
  .gitignore
  docs/img/preprocessing.drawio.svg
  docs/lectures/preprocessing.md
  notebooks/data_acquisition.ipynb
  notebooks/output/.keep
Labels: lecture

#166 Update presentation submission info
  .github/ISSUE_TEMPLATE/presentation-topic.md
  docs/faq.md
  docs/presentations.md
Labels: documentation

#164 Empty __init__ files to make folders be treated as python packages
  src/htwgnlp/__init__.py
Labels: devops

#165 Update tests to validate only expected behavior
  src/htwgnlp/features.py
  tests/htwgnlp/test_features.py
Labels: devops

#169 Check dependencies in Makefile (Issue 135)
  Makefile
  docs/getting_started.md
Labels: devops

#173 Abbreviation Named Entity Recognition in lecture notes
  docs/lectures/introduction.md
  docs/lectures/preprocessing.md
  docs/lectures/word_embeddings.md
  includes/abbreviations.md
Labels: documentation

#174 Adapted `expected` and example output for `print_product_price()`
  src/htwgnlp/python_basics.py
  tests/htwgnlp/test_python_basics.py
Labels: documentation, assignments

#185 getting_started.md adjustments - adding upstream
  docs/getting_started.md
Labels: documentation

#176 add TF-IDF abbreviation
  docs/lectures/preprocessing.md
  includes/abbreviations.md
Labels: documentation

#183 use CBOW abbreviation
  docs/lectures/word_embeddings.md
  includes/abbreviations.md
Labels: documentation

#186 Fix image link in preprocessing lecture
  docs/lectures/preprocessing.md
Labels: documentation

#187 Add question about sample solutions
  docs/faq.md
Labels: documentation

#188 Add make command for pre-commit
  Makefile
Labels: documentation
